"""
This file stores reference data for different parts of site
"""

TAGS = {
    'A': 'pos', 'ADV': 'pos', 'ADVPRO': 'pos', 'ANUM': 'pos', 'APRO': 'pos',
    'COM': 'pos', 'CONJ': 'pos', 'INTJ': 'pos', 'NUM': 'pos', 'PART': 'pos',
    'PR': 'pos', 'S': 'pos', 'SPRO': 'pos', 'V': 'pos', 'praes': 'tense',
    'inpraes': 'tense', 'praet': 'tense', 'nom': 'case', 'gen': 'case',
    'dat': 'case', 'acc': 'case', 'ins': 'case', 'abl': 'case',
    'part': 'case', 'loc': 'case', 'voc': 'case',
    'sg': 'num', 'pl': 'num', 'ger': 'vform',
    'inf': 'vform', 'partcp': 'vform', 'indic': 'vform', 'imper': 'vform',
    'brev': 'aform', 'plen': 'aform', 'poss': 'aform', 'supr': 'degree',
    'comp': 'degree', '1p': 'pers', '2p': 'pers', '3p': 'pers', 'm': 'gender',
    'f': 'gender', 'n': 'gender', 'ipf': 'asp', 'pf': 'asp', 'act': 'voice',
    'pass': 'voice', 'tran': 'trans', 'intr': 'trans', 'parenth': 'type',
    'praed': 'type', 'abbr': 'type', 'mf': 'type', 'awkw': 'form',
    'dist': 'form', 'geo': 'sem', 'persn': 'sem', 'patrn': 'sem',
    'famn': 'sem', 'obsc': 'style', 'inform': 'style', 'rare': 'style',
    'obsol': 'style'}

ACCENTS = {
    'А́': 'А', 'Е́': 'Е', 'И́': 'И', 'О́': 'О', 'У́': 'У', 'Ы́': 'Ы',
    'Э́': 'Э', 'Ю́': 'Ю', 'Я́': 'Я', 'Ё': 'Ё',
    'а́': 'а', 'е́': 'е', 'и́': 'и', 'о́': 'о', 'у́': 'у',
    'ы́': 'ы', 'э́': 'э', 'ю́': 'ю', 'я́': 'я', 'ё': 'ё'}

CATEGORIES = {
    "russian": {
        "A": "pos", "ADV": "pos", "ADVPRO": "pos", "ANUM": "pos",
        "APRO": "pos", "COM": "pos", "CONJ": "pos",
        "INTJ": "pos", "NUM": "pos", "PART": "pos", "PR": "pos",
        "S": "pos", "SPRO": "pos", "V": "pos",
        "praes": "tense", "inpraes": "tense", "praet": "tense",
        "anim": "animacy", "inan": "animacy",
        "acc": "case", "gen": "case", "nom": "case", "dat": "case",
        "ins": "case", "loc": "case", "abl": "case",
        "voc": "case", "part": "case", "pl": "num", "sg": "num",
        "1p": "pers", "2p": "pers", "3p": "pers",
        "ger": "vF", "inf": "vF", "partcp": "vF", "indic": "mood",
        "imper": "mood", "plen": "adjF",
        "brev": "adjF", "poss": "adjF", "comp": "adjF", "supr": "adjF",
        "act": "voice", "pass": "voice",
        "f": "gender", "m": "gender", "n": "gender", "mf": "gender",
        "ipf": "asp", "pf": "asp", "tran": "trans",
        "intr": "trans", "parenth": "sem", "geo": "sem", "persn":
            "sem", "patrn": "sem", "famn": "sem",
        "awkw": "type", "dist": "type", "praed": "type", "rare": "type",
        "abbr": "type", "obsc": "style",
        "inform": "style", "obsol": "style", "bastard": "type"}}

PM_CATEGORIES = {
    'pres':'praes',
    'past':'praet',
    'futr':'praes',
    'tran':'tran',
    'intran':'intr',
    'perf':'pf',
    'impf':'ipf',
    "nomn":'nom',
    "gent":'gen',
    "datv":'dat',
    "accs":'acc',
    "ablt":'ins',
    "loct":'loc',
    "voct":'voc',
    "gen2":'gen',
    "acc2":'acc',
    "loc2":'loc',
    "ADJF":'A',
    "ADJS": 'A',
    "ADVB":"ADV",
    "PRED":'ADVPRO',
    "COMP":'COM',
    "CONJ":'CONJ',
    "NUMR":'NUM',
    "PRTF":'PART',
    "PRTS":'PART',
    "PREP":'PR',
    "NOUN":'S',
    "NPRO":'SPRO',
    "GRND":'V',
    "INFN": 'V',
    "VERB": 'V',
    "PRCL":"PART",
    "INTJ":'INTJ',
    "UNKN":"awkw",
    "1per": "1p",
    "2per": "2p",
    "3per": "3p",
    "inan": "inan",
    "anim": "anim",
    "neut sing":"n,sg",
    "neut plur":"n,pl",
    "femn sing":"f,sg",
    "femn plur":"f,pl",
    "masc plur":"m,pl",
    "masc sing":"m,sg",
    "Name sing":"sg",
    "Name plur":"pl",
    "Geox sing":"sg",
    "Geox plur":"pl",
    "Fixd sing":"sg", 
    "Fixd plur":"pl",
    "1per sing":"1p,",
    "1per plur":"1p",
    "2per sing":"2p",
    "2per plur":"2p,pl",
    "3per sing":"3p,sg",
    "3per plur":"3p,pl", 
    "Anph sing":"sg", 
    "Anph plur":"pl",
}
